### ISSUE TITLE
Add a license so code can be integrated in other repos

### ISSUE THREAD

**Issue by pdejorge** [kartikgupta-at-anu/spline-calibration#3]
Hi! Very interesting work. I was wondering if it could be possible for you to add a license (e.g. MIT license) so that other researchers may build on your code and integrate it in their repositories without copyright infringement. 

Note by default if there is no license "nobody else can copy, distribute, or modify your work". 

See here: https://choosealicense.com/no-permission/

**Comment by pravincoder** [comment]
I can do this for you sir!😎
But can you be more precise on what type of licence you need for your repo pls have quick read on this [GitHub licence a repo blog](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by pdejorge** [comment]
Thank you for the quick response! The MIT license would be great :)

**Comment by pravincoder** [comment]
on it then ! @pdejorge 🤘

**Comment by kartikgupta-at-anu** [comment]
@pdejorge I am checking with our Google colleagues whether they are happy for us to add MIT License, since this work was part of a collaboration. Will get back soon.
